-- LAST 10 DAYS
SELECT SYSDATE, LEVEL-1 AS LEVEL_NUM, TRUNC(SYSDATE) - (LEVEL-1) AS DAYS 
FROM DUAL
CONNECT BY LEVEL <= 10
;




-- LAST 100 END OF MONTH
SELECT TRUNC(SYSDATE) AS DATE_01
        ,(LEVEL-1) AS LEVEL_NUM
        ,ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) AS END_OF_MONTH_01 -- INCLUDES CURRENT MONTH
        ,ADD_MONTHS( LAST_DAY( ADD_MONTHS( TRUNC(SYSDATE),-1 ) ), - (LEVEL-1) ) AS END_OF_MONTH_02 -- EXCLUDES CURRENT MONTH
FROM DUAL
CONNECT BY LEVEL <= 100
;




-- LAST 100 END OF MONTH (SETTING THE STARTING DATE) 
SELECT *
FROM
    (
    SELECT TRUNC(SYSDATE) AS DATE_01
            ,(LEVEL-1) AS LEVEL_NUM
            ,ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) AS END_OF_MONTH_01 -- INCLUDES CURRENT MONTH
            ,ADD_MONTHS( LAST_DAY( ADD_MONTHS( TRUNC(SYSDATE),-1 ) ), - (LEVEL-1) ) AS END_OF_MONTH_02 -- EXCLUDES CURRENT MONTH
    FROM DUAL
    CONNECT BY LEVEL <= 100
    )
WHERE 1=1
    AND END_OF_MONTH_02 >= TO_DATE('31122017','DDMMYYYY')
    
ORDER BY END_OF_MONTH_02
;
