-- LAST 10 DAYS
SELECT SYSDATE, LEVEL-1 AS LEVEL_NUM, TRUNC(SYSDATE) - (LEVEL-1) AS DAYS 
FROM DUAL
CONNECT BY LEVEL <= 10
;




-- LAST 100 END OF MONTH
SELECT TRUNC(SYSDATE) AS DATE_01
        ,(LEVEL-1) AS LEVEL_NUM
        ,ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) AS END_OF_MONTH_01 -- INCLUDES CURRENT MONTH
        ,ADD_MONTHS( LAST_DAY( ADD_MONTHS( TRUNC(SYSDATE),-1 ) ), - (LEVEL-1) ) AS END_OF_MONTH_02 -- EXCLUDES CURRENT MONTH
FROM DUAL
CONNECT BY LEVEL <= 100
;




-- LAST 100 END OF MONTH (SETTING THE STARTING DATE) 
SELECT *
FROM
    (
    SELECT TRUNC(SYSDATE) AS DATE_01
            ,(LEVEL-1) AS LEVEL_NUM
            ,ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) AS END_OF_MONTH_01 -- INCLUDES CURRENT MONTH
            ,ADD_MONTHS( LAST_DAY( ADD_MONTHS( TRUNC(SYSDATE),-1 ) ), - (LEVEL-1) ) AS END_OF_MONTH_02 -- EXCLUDES CURRENT MONTH
    FROM DUAL
    CONNECT BY LEVEL <= 1000 -- THE BIGGER IS BETTER IN THIS CASE.
    )
WHERE 1=1
    AND END_OF_MONTH_02 >= TO_DATE('31122017','DDMMYYYY')
    
ORDER BY END_OF_MONTH_02
;




-- NEXT 10 DAYS
SELECT SYSDATE, LEVEL-1 AS LEVEL_NUM, TRUNC(SYSDATE) + (LEVEL-1) AS DAYS 
FROM DUAL
CONNECT BY LEVEL <= 10
;




-- NEXT 10 END OF MONTH
SELECT TRUNC(SYSDATE) AS DATE_01
        ,(LEVEL-1) AS LEVEL_NUM
        ,ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), (LEVEL-1) ) AS END_OF_MONTH
FROM DUAL
CONNECT BY LEVEL <= 10
;




-- FOR QUARTERS
SELECT END_OF_QUARTER_V1
        ,TO_CHAR(END_OF_QUARTER_V1, 'YYYY') || '-Q' || TO_CHAR(END_OF_QUARTER_V1,'Q') AS END_OF_QUARTER_V2 -- CONVERTS DATE TO YYYY-Q FORMAT
FROM
    (
    SELECT ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) AS END_OF_QUARTER_V1
    FROM DUAL
    CONNECT BY LEVEL <= 36
    )
WHERE 1=1
    AND MOD(EXTRACT(MONTH FROM END_OF_QUARTER_V1),3) = 0 -- FILTERS ONLY QUARTER ENDS
;




-- END OF YEARS
SELECT *
FROM
    (
    SELECT ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) AS END_OF_YEARS
            ,EXTRACT(YEAR FROM ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), - (LEVEL-1) ) ) AS YEARS_YYYY
    FROM DUAL
    CONNECT BY LEVEL <= 100
    )
WHERE 1=1
    AND EXTRACT(MONTH FROM END_OF_YEARS) = 12 -- FILTERS LAST MONTH OF THE YEAR
;




-- FOR YEARS
SELECT EXTRACT(YEAR FROM SYSDATE) - (LEVEL-1)  AS YEARS
FROM DUAL
CONNECT BY LEVEL <= 10
;

