-- FIRST THURSDAY BEFORE END OF NEXT MONTH (END OF NEXT MONTH IS NOT EXCLUDED/INCLUDED) WITH PL/SQL
DECLARE
    V_DATE_01 DATE := TO_DATE('25082021' ,'DDMMYYYY');
    V_START_DATE DATE;
    V_END_DATE DATE;
    V_RESULT_DATE DATE; -- END OF NEXT MONTH IS INCLUDED
    V_RESULT_DATE2 DATE; -- END OF NEXT MONTH IS NOT INCLUDED
BEGIN
    V_START_DATE := TRUNC(ADD_MONTHS(V_DATE_01,1),'MONTH');
    V_END_DATE := LAST_DAY(ADD_MONTHS(V_DATE_01,1));
    WHILE V_START_DATE <= V_END_DATE -- BEGINS FROM FIRST DAY OF NEXT MONTH (ALSO IT IS POSSIBLE TO START 3RD WEEK START)
    LOOP

        IF TO_CHAR(V_START_DATE ,'D') = 5 THEN
            V_RESULT_DATE := V_START_DATE; -- WHEN IT FINDS IT IS THURSDAY IT ASSINGS VALEUE TO V_RESULT_DATE
        END IF;
        
        IF TO_CHAR(V_START_DATE ,'D') = 5 AND V_START_DATE != LAST_DAY(V_START_DATE) THEN
            V_RESULT_DATE2 := V_START_DATE; -- WHEN IT FINDS IT IS THURSDAY IT ASSINGS VALEUE TO V_RESULT_DATE2
        END IF;
        
        V_START_DATE := V_START_DATE + 1;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('V_RESULT_DATE >> ' || V_RESULT_DATE);
    DBMS_OUTPUT.PUT_LINE('V_RESULT_DATE2 >> ' || V_RESULT_DATE2);
END;
/
